server:
  port: 9000
  servlet:
    context-path: /auth-server

spring:
  application:
    name: auth-server
  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: 123456
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 2
        max-wait: 3000ms
        max-idle: 2
        min-idle: 0

management:
  endpoint:
    health:
      enabled: true