server:
  port: 9000
  servlet:
    context-path: /auth-server

spring:
  application:
    name: auth-server
  # redis
  redis:
    database: 0
    host: localhost
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: 123456
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 2
        max-wait: 3000ms
        max-idle: 2
        min-idle: 0

mybatis:
  # 配置实体映射类所在包名
  type-aliases-package: org.ylc.frame.cloud.authserver.entity
  # 配置mapper xml文件所在路径，这里是一个数组
  # classpath 只会到你的class路径中查找找文件;
  # classpath* 不仅包含class路径，还包括jar文件中(class路径)进行查找
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启驼峰类型的命名规则
    map-underscore-to-camel-case: true

management:
  endpoint:
    health:
      enabled: true