server:
  port: 8090
eureka:
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 从本地文件读取
## 需要配置`spring.profiles.active=native`，默认会从resources路径下读取配置文件。
## 通过`spring.cloud.config.server.native.search-locations`可以指定配置文件
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        # 可以配置在项目下或者本地磁盘如: file:D:\\repo
#        native:
#          search-locations: classpath:/repo

# 从 git读取配置文件
spring:
  application:
    name: config-server
  # 用户认证
  security:
    user:
      name: admin
      password: admin2020
  cloud:
    config:
      server:
        # 从git仓库获取配置文件，如果是私有仓库需要填写用户密码
        git:
          uri: https://github.com/yulc-coding/spring-cloud-demo
          # git仓库地址下的相对地址，可以使用通配符*如/test*，多个用逗号","分割，会从根目录以及配置的目录下去查找
          search-paths: /repo
          # username:
          # password:
          # 启动项目是就clone git仓库
          clone-on-start: true
# 方便查看执行流程
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.boot: debug
