server:
  port: 8850
spring:
  application:
    name: cmpt-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  cloud:
    # 服务消费方订阅服务提供方的应用名称的列表，多个，使用 "," 分割。 默认值为 "*"（不推荐），它将订阅所有应用。
    subscribed-services: cmpt-dubbo-provider