server:
  port: 8761
eureka:
  instance:
    # eureka服务实例名称
    hostname: eureka1
  client:
    # 不向注册服务中心注册自己（自己就是服务中心）
    register-with-eureka: false
    # 不需要去检索注册表信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/