#server:
#  port: 8762
#  servlet:
#    context-path: /gateway
#spring:
#  application:
#    name: cmpt-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          # 开启从注册中心动态创建路由的功能
#          enabled: true
#          # 在断言或者过滤器服务名使用小写，默认是大写
#          lower-case-service-id: true
#      routes:
#        # 路由的ID，保持唯一
#        - id: upms
#          # 匹配后路由地址，此处需要使用lb协议，这样才能启用Gateway的负载均衡功能
#          uri: lb://upms
#          # 断言配置
#          predicates:
#            # 路径相匹配的进行路由
#            - Path=/upms/**
#          # 过滤器配置
#          filters:
#            # 去除指定数量的路径的前缀，这里设为1，即去掉请求路径中的/upms/
#            #- StripPrefix=1
#            # 服务降级
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
#logging:
#  level:
#    org.springframework.cloud.gateway: debug