server:
  port: 8091

eureka:
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, bus-env

spring:
  cloud:
    bus:
      id: ${spring.application.name}:${server.port}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest