server:
  port: 8760
spring:
  application:
    name: eureka-client
eureka:
  instance:
    # 实例显示信息
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/