server:
  port: 8082
spring:
  application:
    name: feign
eureka:
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# 开启熔断机制
feign:
  hystrix:
    enabled: true
# 选择要开放的页面节点  默认只开启了health、info两个节点
# *代表开启所有，yml文件中 * 需要加双引号 -> "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"