server:
  port: 8083
spring:
  application:
    name: turbine
eureka:
  instance:
    # 以IP地址注册到服务中心，相互注册使用IP地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  # 需要监控的服务名，多个用 , 隔开
  app-config: ribbon, feign
  aggregator:
    # 集群名称列表，默认 default
    cluster-config: default
  # 指定集群名称，注意这里需要以`new String("default")`的形式配置，
  # 否则会报异常: Property or field 'default' cannot be found on object of type 'com.netflix.appinfo.InstanceInfo
  cluster-name-expression: new String("default")
